---
title: "BARAN AKYOL TIME SERIES HW5"
output: pdf_document
---

```{r setup, include=FALSE}
library(xts)
library(TTR)
```

## HW 5

```{r, echo=TRUE}
data <- read.csv("/Users/mehmetyilmaz/Desktop/R/dataHW5csv.csv")
data[data == "NaN"] = NA
```

##  Part a) convert to log-returns
```{r 1 minute logreturn, echo=TRUE}

oneminuteP<- t(data[,3:393])
dataframe<- data.frame(data[,2:393])
row.names(dataframe) <- data[,1]
dataframe<- dataframe[complete.cases(dataframe),]
dataframe<- xts(dataframe,order.by = as.Date(row.names(dataframe),format = '%m/%d/%Y'))

oneminutereturns <- 100*diff(log(t(dataframe[,2:392])))
oneminutereturns <- t(oneminutereturns)

oneminutereturns <- xts(oneminutereturns,order.by = as.Date(index(dataframe)),format = '%m/%d/%Y')
oneminutereturns <- oneminutereturns[complete.cases(oneminutereturns),]
```



## Part b) estimate pacf

```{r part b, echo=TRUE}


y=as.matrix(oneminutereturns)
pacfmatrix<-matrix(nrow=650,ncol=10)

for (i in 1:650){
  
  pacf<-pacf(y[i,],lag.max = 10,plot=FALSE)
  pacfmatrix[i,1:10]<- pacf$acf[1:10]
  
}
head(pacfmatrix)
```

## part c) Boxplot of pacf
```{r}

boxplot(pacfmatrix,las=2,names=c('lag 1','lag 2','lag 3','lag 4','lag 5','lag 6','lag 7','lag 8','lag 9','lag10'),col= 'royalblue2')


```
## As can be seen from the box plot and a quick glance at the matrix, the first order pacf is in fact negative on a typical day

## Part d) open, low, high, close price for every day

```{r}
pricematrix<- matrix(nrow=672,ncol=4)
colnames(pricematrix)<- c('Open','Low','High','Close')
rownames(pricematrix)<-data[,1]
data[is.na(data)] <- 0

for (i in 1:672){
    pricematrix[i,2]<-data[i,which.min(data[i,3:393])]
    pricematrix[i,3]<-data[i,which.max(data[i,3:393])]
}
pricematrix[,1]<-data[,3]
pricematrix[,4]<-data[,393]
OHLC<-as.data.frame(pricematrix)
head(OHLC)

```


## Part e) Estimate daily volatilities
```{r}


volfunction <- function (O,L,H,C_1,C_0) { 
sad <- 0.12 * ((O - C_0)^2)/0.66
tas <- 0.88 * (0.5 * ((H-L)^2) - ((2*log(2) - 1)*((C_1-O)^2))) / (1-0.66) 
result <- sad + tas 
return(result)
}

VolEs=matrix(nrow=671,ncol=1)

for (i in 1:671){  
  VolEs[i]= volfunction(
    OHLC[i+1,1],OHLC[i+1,2],OHLC[i+1,3],OHLC[i+1,4],OHLC[i,4] )
   }



```

## Part f) Plot Volatility vs PACF
```{r}

plot(pacfmatrix[,1],VolEs[1:650], xlab = "Partial Auto Correlation", ylab = "Volatility",main = "Volatility vs Pacf")
```

