---
title: "Project for Statistical Inference and Time-Series Modeling Course"
author: "Baran AkyolL]"
date: "New York, `r Sys.Date()`"
output:
  word_document:
    toc: yes
  pdf_document:
    number_sections: yes
    toc: yes
  html_document:
    toc: yes
---
### Preliminaries
Load the required packages.
```{r}
#here put an r code which loads the requested packages
library("xts") 
library("fBasics")
library("psych")
library(ggplot2)
library(plotly)
library(dygraphs)
library(zoo)

```

## Set working directory
```{r}

```

##Load the APPLE data
```{r}
AAPL <- read.csv(paste(getwd(),"/AAPL.txt",sep=''))
```

## Convert the column with dates into Date format
```{r}
D <- AAPL[,1]
D <- as.Date(toString(AAPL[1,1]),'%Y%m%d')
for (t in 2:dim(AAPL)[1])
    D <- c(D,as.Date(toString(AAPL[t,1]),'%Y%m%d'))
```

## Convert the data frame into xts object ordered by date in vector D
```{r}
AAPL_xts <- xts(AAPL[,"CLOSE"], order.by = D)
```


## Compute log-returns from close prices of APPLE stock
```{r}
r_AAPL <- diff(log(AAPL_xts[,"CLOSE"]))
```


## Read the tickers for the data
```{r}
ticker <- read.table(paste(getwd(),"/Tickers.txt",sep=''), header=FALSE)
```

## question1
```{r}
data_xts <- AAPL_xts
for (k in 3:dim(ticker)[1])
{
  prices <- read.csv(paste(getwd(),"/", ticker$V1[k], ".txt", sep =''))
  dates <- NULL;
  dates <- as.Date(toString(prices[1,1]),'%Y%m%d')
  for (t in 2:dim(prices)[1])
      dates <- c(dates,as.Date(toString(prices[t,1]),'%Y%m%d'))
  prices_xts <- xts(prices[,"CLOSE"],order.by = dates)
  data_xts<-merge(data_xts, prices_xts)
}
names(data_xts) = paste("CLOSE", ticker[2:nrow(ticker),"V1"], sep=".")
Logreturn = as.data.frame(lapply(data_xts, FUN=function(x) diff(log(x))))
```


## question 2 to 5
```{r}
library(psych)
library(gplots)
resume = describe(Logreturn, na.rm=T, skew=T, type=3, check=T)
q2 = data.frame(resume[,c("vars", "n","mean", "median", "sd")], 
                   var=resume$sd^2, 
                   resume[,c("skew","kurtosis")])

# because samples size are higher than 30 then normal approx will be used
z = qnorm(1-0.05/2)
q3 = data.frame(resume[,c("vars", "n","mean", "se")], 
                lb=resume$mean - z*resume$se,
                ub=resume$mean + z*resume$se)
q3$sig = ifelse(q3$lb<0 & q3$ub>0, "no", "yes") # significant diff from 0 at 5%
plotCI(x=q3$mean, uiw=z*q3$se, col="black", barcol="blue", ylab="Mean Logreturn", xlab=" ", 
         labels=round(q3$mean,-3), xaxt="n", xlim=c(0,100), pch=16, cex=0.5, gap=0.2)
axis(side=1, at=1:100, labels=t(ticker[-1,]), cex=0.1)
table(q3$sig) 



q4 = data.frame(resume[,c("vars", "n", "skew")],
                se.skew = (6*resume$n*(resume$n-1)/((resume$n-2)*(resume$n+1)*(resume$n+3)))^0.5
                )
q4 = within(q4, {
  lb.skew = skew - 2*se.skew 
  ub.skew = skew + 2*se.skew
  })

q4$sig = ifelse(q4$lb.skew<0 & q4$ub.skew>0, "no", "yes") # significant diff from 0 at 5%
table(q4$sig)

plotCI(x=q4$skew, uiw=2*q4$se.skew, col="black", barcol="blue", ylab="Skew Logreturn", xlab=" ",
         xaxt="n", xlim=c(0,100), pch=16, cex=0.5, gap=0.2)
axis(side=1, at=1:100, labels=t(ticker[-1,]), cex=0.1)
 

# the same for kurtosis we use the formula of standard error
q5 = data.frame(resume[,c("vars", "n", "kurtosis")],
                se.kurtosis = 2*q4$skew*((resume$n^2-1)/((resume$n-3)*(resume$n+5)))^0.5
                )
q5 = within(q5, {
  lb.kurtosis = kurtosis - 2*se.kurtosis
  ub.kurtosis = kurtosis + 2*se.kurtosis
  })
q5$sig = ifelse(q5$lb.kurtosis < 0 & q5$ub.kurtosis > 0, "no", "yes") # significant diff from 0 at 5%
table(q5$sig) 
plotCI(x=q5$kurtosis, uiw=2*q4$se.kurtosis, col="black", barcol="blue", 
       ylab="kurtosis Logreturn", xlab=" ", xaxt="n", xlim=c(0,100), pch=16, cex=0.5, gap=0.2)
axis(side=1, at=1:100, labels=t(ticker[-1,]), cex=0.1)

```


## question 6 to 8

```{r}

# q5 = Return.annualized(data_xts, scale = 252, geometric = F)
q678 = describe(data_xts, fast=TRUE)[,1:4]
q678 = within(q678, {
  annualized.mean = mean*252
  annualized.sd   = sd*sqrt(252)
  shape.ratio     = annualized.mean/annualized.sd
})


p = ggplot(q678, aes(x=rownames(q678), y=shape.ratio)) + geom_point(colour="blue", size=2) + 
  theme_bw() + theme(axis.title.x = element_blank(), 
                     axis.text.x  = element_blank(),
                     axis.ticks.x = element_blank())
ggplotly(p)

```

##Project
##1
```{r}
LogAAPL=diff(log(AAPL_xts))
roll_AAPL = rollapply(data=LogAAPL, width=252, FUN=mean, na.rm= T, fill=NA)

rollmean = rollapply(data=Logreturn, width=252, FUN=mean, na.rm= T, fill=NA)
rollSd = rollapply(data=Logreturn, width=252, FUN=sd, na.rm= T, fill=NA)
rollVar = rollapply(data=Logreturn, width=252, FUN=var, na.rm= T, fill=NA)
rollMedian=rollapply(data=Logreturn, width=252, FUN=median, na.rm= T, fill=NA)
rollSkewness=rollapply(data=Logreturn, width=252, FUN=skewness, na.rm= T, fill=NA)

```
##2
```{r}
#MDLZ MONDELEZ INTERNATIONAL INC has highest Sharpie Ratio
MDLZ <- read.csv(paste(getwd(),"/MDLZ.txt",sep=''))
D <- MDLZ[,1]
D <- as.Date(toString(MDLZ[1,1]),'%Y%m%d')
for (t in 2:dim(MDLZ)[1])
    D <- c(D,as.Date(toString(MDLZ[t,1]),'%Y%m%d'))

MDLZ_xts <- xts(MDLZ[,"CLOSE"], order.by = D)
LogMDLZ <- as.data.frame(lapply(MDLZ_xts, FUN=function(x) diff(log(x))))

rollMDLZmean = as.data.frame.ts(rollapply(data=LogMDLZ, width=252, FUN=mean, na.rm= T, fill=NA))
MDLZmean_xts <- xts(rollMDLZmean[,1],order.by=D)

rollMDLZSd = as.data.frame(rollapply(data=LogMDLZ, width=252, FUN=sd, na.rm= T, fill=NA))
rollMDLZVar = as.data.frame(rollapply(data=LogMDLZ, width=252, FUN=var, na.rm= T, fill=NA))
rollMDLZMedian=as.data.frame(rollapply(data=LogMDLZ, width=252, FUN=median, na.rm= T, fill=NA))
rollMDLZSkewness=as.data.frame(rollapply(data=LogMDLZ, width=252, FUN=skewness, na.rm= T, fill=NA))


dygraph(MDLZmean_xts) %>%
dyOptions(axisLineWidth = 1.5, fillGraph = FALSE, drawGrid = T, rightGap=50) %>%
dyRangeSelector()


```




